### ISSUE TITLE
Does not work with Brave

### ISSUE THREAD

**Issue by CryptoD** [anonaddy/browser-extension#11]
Extension does not show in the tool bar after installation. I can see it in the extensions list but that's about it. 

Version of extension: 1.0.15
Version of browser: Version 1.13.86 Chromium: 85.0.4183.102 (Official Build) (64-bit)

**Comment by willbrowningme** [comment]
Thanks, will investigate this as soon as I can.

**Comment by willbrowningme** [comment]
Please could you update to v1.1.1 of the extension and see if this issue still exists?
