### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by jakob11git** [anonaddy/browser-extension#12]
Apparently since the newly released Safari 14 there is (some?) support for extensions using the WebExtensions API, see: https://developer.apple.com/news/?id=kuswih5l

It would be great to be able to use the AnonAddy extension in Safari.

**Comment by willbrowningme** [comment]
Will look into this shortly, thanks for bringing it up.

**Comment by alexsde** [comment]
@willbrowningme I've adapted this extension to Safari for myself. I can publish the code if you are interested? It also works on iOS and iPadOS on the latest betas :)

**Comment by willbrowningme** [comment]
@alexsde Yes that would be great, will check out shortly!

**Comment by willbrowningme** [comment]
I've created a developer account with Apple so just need to figure out how to publish the extension now, will give credit to you for the adaptation @alexsde thanks.

**Comment by willbrowningme** [comment]
@alexsde do you know if it's possible to publish an extension to the app store without using Xcode? It seems it is only available on MacOS.

**Comment by alexsde** [comment]
@willbrowningme it's not, unfortunately. You need a Mac to build and submit the binary to the App Store.

**Comment by jeifour** [comment]
One alternative to buying a physical Mac could be to rent a Mac in the cloud. Offered by many classical providers (AWS, Scaleway) and there are also companies specialized in this like MacStadium.

**Comment by willbrowningme** [comment]
Good idea, I'll check that out, thanks!

**Comment by teeruku-github** [comment]
Any update on this ?

**Comment by marcolaux** [comment]
I guess this can get closed now

**Comment by jakob11git** [comment]
Indeed. https://apps.apple.com/app/addy-io-extension/id6670220050
