### ISSUE TITLE
Visualize existing aliases

### ISSUE THREAD

**Issue by xplosionmind** [anonaddy/browser-extension#15]
To me it's much more useful to have my already generated addresses always at hand in the extension than having the possibility to generate them quickly.

Something as simple as a plain text list would do, and adding a copy button would be enough make it perfect.

Thanks a lot!
T

**Comment by willbrowningme** [comment]
This is on the roadmap here - https://github.com/anonaddy/anonaddy/projects/1#card-52584416

Will try to add it as soon as I can.

**Comment by xplosionmind** [comment]
Thanks a lot!
