### ISSUE TITLE
How to commit

### ISSUE THREAD

**Issue by grandeljay** [anonaddy/browser-extension#16]
Hey,

I am unfamiliar with the process of software development and just forked this repo and added Sidebar support. However, I am unable to commit to my fork. Am I missing something obvious?

```
D:\XAMPP\htdocs\browser-extension>git commit
husky > pre-commit (node v12.18.3)
[STARTED] Preparing...
[SUCCESS] Preparing...
[STARTED] Running tasks...
[STARTED] Running tasks for *.{css,js,vue}
[STARTED] npm run format --
[FAILED] npm run format -- [FAILED]
[FAILED] npm run format -- [FAILED]
[SUCCESS] Running tasks...
[STARTED] Applying modifications...
[SKIPPED] Skipped because of errors from tasks.
[STARTED] Reverting to original state because of errors...
[SUCCESS] Reverting to original state because of errors...
[STARTED] Cleaning up...
[SUCCESS] Cleaning up...

× npm run format --:
[error] No files matching the pattern were found: "'src/assets/**/*.{css,js,vue}'".
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! anonaddy-extension@1.1.5 format: `prettier --write 'src/assets/**/*.{css,js,vue}' "D:/XAMPP/htdocs/browser-extension/src/assets/css/app.css"`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the anonaddy-extension@1.1.5 format script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     \\192.168.10.101\profiles_red$\[...]\AppData\Roaming\npm-cache\_logs\2021-01-26T09_59_08_971Z-debug.log

> anonaddy-extension@1.1.5 format D:\XAMPP\htdocs\browser-extension
> prettier --write 'src/assets/**/*.{css,js,vue}' "D:/XAMPP/htdocs/browser-extension/src/assets/css/app.css"

src\assets\css\app.css 40ms
husky > pre-commit hook failed (add --no-verify to bypass)
```

**Comment by willbrowningme** [comment]
It appears that the pre-commit hook that runs `npm run format` is failing because it can't find anything in `src/assets/...`

Have you staged the files for commit first by running `git add .`

After staging please try running `git commit -m "Your description of the commit here"`

Some good examples available in this post - https://www.hostinger.com/tutorials/basic-git-commands

**Comment by grandeljay** [comment]
Thank you!

I use a GUI for git (GitHub Desktop) but tried the commands with the same result. And the files/directory `/src/assets/**/*` **do** exist.

In case it helps, here's a screenshot of what my GUI gave me.
![GitHub Desktop Error](https://user-images.githubusercontent.com/45571053/105845368-eede7e00-5fda-11eb-8eb7-e6ef19a6d298.png)

It seems to mention lint or a linter, could this be it?

**Comment by willbrowningme** [comment]
Could be related to this issue https://github.com/okonet/lint-staged/issues/577

Try changing the hooks part in package.json to:

```json
"hooks": {
    "pre-commit": "npx lint-staged"
}
```

**Comment by grandeljay** [comment]
Nice find!

I solved my GUI problem by using `npx lint-staged` instead of `int-staged` proposed by @zorzysty in https://github.com/okonet/lint-staged/issues/420#issuecomment-558121775 :
```diff
    "hooks": {
-     "pre-commit": "lint-staged"
+     "pre-commit": "npx lint-staged"
    }
```
_Originally posted by @nelson6e65 in https://github.com/okonet/lint-staged/issues/577#issuecomment-645071705_

Unfortunately, I am still not able to commit and now my GUI is giving me the [same error as the console](https://github.com/anonaddy/browser-extension/issues/16#issue-794098671) did.

**Comment by willbrowningme** [comment]
Hmm, try changing the `lint-staged` section of your `package.json` to the following:

```json
"lint-staged": {
    "*.{css,js,vue}": [
      "prettier --write"
    ]
}
```

**Comment by grandeljay** [comment]
That worked! Thanks a bunch!
