### ISSUE TITLE
Make Browser Extension like Simplelogin

### ISSUE THREAD

**Issue by FrozenVertx** [anonaddy/browser-extension#19]
Hi,
Today I just trying another well-known email-forwarding tool [Simplelogin](https://github.com/simple-login/browser-extension) (OpenSource). I see their extension have everything that needed for productivity. From showing existing alias to auto-generate new alias in email fields. Can you please make your anonaddy extension like that full-featured extension I mean from fork its code or any other way. Those features save much more time for Ex-in case of typing email alias I have to just click on icon on email field or context menu and it pasted like password managers or If I made any alias prior then extension automatically show you made alias on this site.  

I want to stick with anonaddy because I like it So I have a request to upgrade the simple generating browser extension to fully-killer extension.

**Comment by willbrowningme** [comment]
This is currently on the roadmap to improve the features available for the browser extension - https://github.com/anonaddy/anonaddy/projects/1#card-52584416

I will work on this as soon as I can, I just have some other things I need to work on first.

**Comment by FrozenVertx** [comment]
I glad to here that you already work on this.Can you please add to make autofill generate alias option on sites in your to do list. Its very Handy
