### ISSUE TITLE
more nuanced control of recipients in browser extension

### ISSUE THREAD

**Issue by CouldBeThis** [anonaddy/browser-extension#2]
I hope I am able to explain this properly: 

- I have 2 recipients set up. 
- I use the browser extension in 2 different browsers. 
- I would like one browser to generate UUID addresses for one of the recipients. The other browser, the other recipient. 

Is there a way to do this? All I can find is how to update the default recipient globally. 

⭐️ Even better, would be if the extension could have multiple recipients set up and they could be selected as needed. But I imagine that's more complicated. 

thank you for the excellent application.

**Comment by anonaddy** [comment]
I've moved this issue to the browser extension repository.

At the moment this is not possible from the browser extension. I do plan to add much more functionality to the extension going forward.

I'll see what I can do and post updates here.

**Comment by willbrowningme** [comment]
This is now possible with v2 of the extension, currently pending review on Chrome.
