### ISSUE TITLE
Header link always points to app.anonaddy.com

### ISSUE THREAD

**Issue by croxxx** [anonaddy/browser-extension#22]
This is more of a small usability nuisance than a bug, yet I feel it is worth mentioning.

When using this extension with a self-hosted instance of AnonAddy (see #9), I would expect the link in the header to point me to that instance.
However, I noticed the value is hard-coded to app.anonaddy.com. This may be appropiate for most users, but having custom settings reflected would definitely be a nice touch.

I'm not familiar with Vue, so I probably won't be much help myself, but I assume the setting to be persisted *somehow* already for generic functionality (yet I was unable to figure out the data retention mechanism as of now). Reading the stored value and using it instead of the currently hardcoded string feels like it should be rather straightforward, though.

Related code:
https://github.com/anonaddy/browser-extension/blob/3934857059bcb2be1ad3e6d67dd4e84d82c7eadd/src/assets/js/components/App.vue#L119-L125
https://github.com/anonaddy/browser-extension/blob/3934857059bcb2be1ad3e6d67dd4e84d82c7eadd/src/assets/js/components/App.vue#L31-L52

**Comment by willbrowningme** [comment]
Good spot, I'll sort that out shortly.

**Comment by willbrowningme** [comment]
This has been fixed in v2.0.10.
