### ISSUE TITLE
recall the most recently generated alias(es)

### ISSUE THREAD

**Issue by CouldBeThis** [anonaddy/browser-extension#3]
It would be very helpful if the extension was able to recall the most recently created alias. 

This is because when creating accounts, I usually use a password generator. So I copy/paste the email address then I copy/paste the password. Sometimes my password manager catches this and remembers it but especially if there is a problem (re captcha shenanigans, undeclared password requirement or for unknown reasons) it doesn't. 

So I end up creating a new alias with each attempt til finally it works. Logging into the site requires getting out my phone for the 2fa and such. 

If some people don't want this could be opt in/out. 

More robustly, it could remember the last _x_ addresses, or for the last _x_ time. 

I would suggest the display would include the date, time, domain etc, just in case there was any confusion or errors.

**Comment by willbrowningme** [comment]
Great idea, I too run into that issue when using a password manager. I'll add it to my to do list, thanks.

**Comment by willbrowningme** [comment]
This has just been added in v1.1.0 of the browser extension, it's already live on FireFox and is pending on Chrome.

You can quickly see and copy the last alias that was generated using the extension.
