### ISSUE TITLE
Hostname alias option

### ISSUE THREAD

**Issue by dahamsta** [anonaddy/browser-extension#31]
I've switched from SimpleLogin because I prefer your approach with regard to docker-compose, releases, options, etc, however it was only after I'd switched I noticed that the browser plugin doesn't support a hostname option, as SimpleLogin defaults to. That is, on clicking the icon in the browser, the domain name of the website, less the TLD, becomes the alias, and is filled in ready to go. I much prefer this approach as it's easy to see the source of spam, it's easy to remember and say, etc. Could this be added to the extension please? Example attached, when used on your own site.

![2022-08-05_00-53-09](https://user-images.githubusercontent.com/105064689/182974272-cdf5a9a9-4628-4205-9fb4-f6926566b760.jpg)

**Comment by willbrowningme** [comment]
Thanks, I'll see if this is something I can add for self-hosted instances to the extension.

**Comment by dahamsta** [comment]
That would be great, thank you.

**Comment by willbrowningme** [comment]
I've just pushed an update v2.1.1 that now includes suggestions for the alias local part when you select the alias format as 'custom'.

So if you are on app.anonaddy.com you will get the following suggestions `anonaddy, anonaddy.com, app.anonaddy.com`. You simply have to click on a suggestion and it will use that for the local part of the alias.

So clicking on `anonaddy` would fill the local part and you would be able to create the alias `anonaddy@yy.ie` as in your screenshot.

**Comment by dahamsta** [comment]
This is excellent, and you've catered to third-level domains like UK and AU too, that's brilliant!

When you have time, would it be possible to have the plain one - "anonaddy" in this case - filled in automatically? Or perhaps to make one configurable?

One more question, is there a way of donating towards development? I reaslise I could set up an account on anonaddy.com, but I don't actually need one as I'm self-hosting. :)

Thanks very much for adding this so quickly, it was the one major holdback from me.

**Comment by willbrowningme** [comment]
You're welcome, yes I added a package that uses the Public Suffix List to parse the second level domain.

Sure, I can add an option to the settings tab to automatically auto-fill the second level domain (e.g. "anonaddy") in the local part field for whenever the custom format is used.

I also added a suggestion with 3 random alphanumeric characters appended e.g. "anonaddy.h4a" for times when you may want to prevent anyone guessing a pattern for your aliases.

Thanks, that's very generous of you, I have a page setup on the website with some options here - https://anonaddy.com/donate/

**Comment by dahamsta** [comment]
> You're welcome, yes I added a package that uses the Public Suffix List to parse the second level domain.

Learn something new every day, I've bookmarked that thanks.

> Sure, I can add an option to the settings tab to automatically auto-fill the second level domain (e.g. "anonaddy") in the local part field for whenever the custom format is used.

That would be great! I have one other note about using Custom, sorry if I'm overloading you -- when Custom is selected, the Create Alias button is below the fold in the popup, so you have to scroll before clicking. It seems to be variable for some reason, but there's nearly always a scrollbar. Making the popup a little taller or tightening up the padding would help.

![2022-08-16_20-39-20](https://user-images.githubusercontent.com/105064689/184968190-2c6e672b-eefc-4ee2-aa48-77e6b41d6e09.jpg)

> I also added a suggestion with 3 random alphanumeric characters appended e.g. "anonaddy.h4a" for times when you may want to prevent anyone guessing a pattern for your aliases.

I spotted that, nice.

> Thanks, that's very generous of you, I have a page setup on the website with some options here - https://anonaddy.com/donate/

Completely forgot, just about to do that now! :)

**Comment by willbrowningme** [comment]
Thanks very much! Yes good spot, I'll see if I can sort the button being below the fold next week along with the auto-filled local part setting.

**Comment by willbrowningme** [comment]
Just pushed this update live v2.1.3, should be available on Firefox already, may take a while on Chrome. Let me know what you think. Hopefully the small adjustments to width and padding will be enough to keep the create alias button above the fold.

**Comment by dahamsta** [comment]
Looks good so far, working well. I'm sure I'll be back again with other niggles, but I'll leave you alone for now, thanks very much for your help.
