### ISSUE TITLE
v2.1.3 Domain with random extenstion set, only creates domain, but no random extension?

### ISSUE THREAD

**Issue by mannp** [anonaddy/browser-extension#32]
Using brave with v2.1.3 extension with AA Lite subscription.

Wondered if i might be doing anything wrong, else a bug?

Thanks.

**Comment by willbrowningme** [comment]
Do you mean the "Automatically Fill New Alias Local Parts When Using Custom Format" setting? 

So if you create an alias for say example.com it just makes example@yourdomain.com instead of example.5ra@yourdomain.com?

**Comment by mannp** [comment]
I find the ui settings rather confusing in the extension.

In its options I have selected domain + random letters as the default.

When I click + to create a new alias, there is no option for that, only domain, random letters, random words and custom (from memory)

Here I select custom and cannot get further without entering anything in the custom field.

I have to select domain and that creates domain@ even though the default is set to domain+random letters in the settings.

So yes your last para is the outcome.

**Comment by mannp** [comment]
Sure...did I miss something from the docs, as it is not a logical layout at all. 

It also means the only way it will work is if you have custom set at the global level, which seems counter intuitive when there are additional settings in the extension.

Just feels like a make do bolt on, rather than just being able to select domain-4gh in the extension config.

Anyway, just some noob feedback.

**Comment by willbrowningme** [comment]
I've just pushed a new version v2.1.4 that improves this behaviour, it should be live on Chrome and Firefox shortly.

**Comment by mannp** [comment]
> I've just pushed a new version v2.1.4 that improves this behaviour, it should be live on Chrome and Firefox shortly.

Many thanks @willbrowningme appreciated, will give it a try 👍🏻

**Comment by mannp** [comment]
@willbrowningme immediately updating the domain.random characters on selecting custom makes more sense and does the job, thank you.
