### ISSUE TITLE
Custom domain not in list

### ISSUE THREAD

**Issue by fungs** [anonaddy/browser-extension#34]
Great work for everything you do!!

I've created a working custom domain and can create aliases in the web app as well as in the Android app (f-droid external app). When using the browser extension in firefox, it does not show the domain when I want to create a new alias.

Version: 2.1.6

Thanks!

**Comment by willbrowningme** [comment]
Please click on the settings tab and then click "Refresh Domains and Defaults".

**Comment by fungs** [comment]
Great, it work :)

Didn't see this option. I understand that you want to keep the traffic and latency low. Wouldn't it be better to generate something like a configuration hash or similar and automatically reload if that changes?

**Comment by willbrowningme** [comment]
Great, yes you're right, I'll see if I can sort something out in the near future.
