### ISSUE TITLE
dialog box for firefox is half the height or the one for brave...can create alias

### ISSUE THREAD

**Issue by mannp** [anonaddy/browser-extension#35]
Hi there

In firefox when i select the aa extension the window created is only half of the height of the one created for brave.

The result is I am unable to create an alias in ff as the scrollbar on the ff window does not go down as far as the 'create alias' button :-/

Is this any likely reason for the odd behaviour in ff?

Thanks

**Comment by willbrowningme** [comment]
I can't reproduce this. Do you have a screenshot you can share?

**Comment by mannp** [comment]
I do, I just need to figure out how to redact all of the full aliases that are shown.

**Comment by willbrowningme** [comment]
Closing for now as I don't think this is still an issue.
