### ISSUE TITLE
option to default to "random words" format vs uuid

### ISSUE THREAD

**Issue by CouldBeThis** [anonaddy/browser-extension#4]
Is there a reason to prefer uuid to random words?

- they are easier to read for humans = less prone to error
- occasionally a website will accept words but not uuid
- they are shorter

I'd like to use them by default if there is no reason why not to

**Comment by willbrowningme** [comment]
Great idea.

I can add this as an option in settings. It would work in the same way as selecting a default domain for new aliases.

**Comment by willbrowningme** [comment]
I've just added this feature, you can find it in your account settings underneath the default domain option.
