### ISSUE TITLE
Search Aliases: "Load more" fails if search string less than 3 characters.

### ISSUE THREAD

**Issue by DavidPesticcio** [anonaddy/browser-extension#41]
While typing a string into _**Search aliases**_ box, unless the search string length is >= 3 characters, selecting _**Load more**_ will fail with the following error: `An Error Has Occurred`

To replicate the behaviour type the following two test cases into _**Search aliases**_:

Search string: `@a`
Upon selecting _**Load more**_ this fails with `An Error Has Occurred`

Search string: `@an`
Upon selecting _**Load more**_ this succeeds to load more aliases

**Comment by willbrowningme** [comment]
Thanks, will sort this shortly!

**Comment by willbrowningme** [comment]
Fixed in v2.2.4.
