### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by petcat30** [anonaddy/browser-extension#44]
Hey, 

It seems like the search has stopped working? I have tried on LibreWolf and Brave. It just shows all my aliases when I enter a search term.

![image](https://github.com/anonaddy/browser-extension/assets/108421858/4606d2b8-ef17-4840-897f-74e7467406f3)

**Comment by willbrowningme** [comment]
Thanks for letting me know, I've just fixed this in v2.2.5 that should be live shortly.

**Comment by cmbail** [comment]
Just updated and confirm it's fixed.
