### ISSUE TITLE
ALIASES Show: drop-down not functioning correctly

### ISSUE THREAD

**Issue by DavidPesticcio** [anonaddy/browser-extension#47]
### Problem observed:

The list of aliases does not update correctly when cycling through each entry in the **"Show:"** drop-down, from **"All"** through to **"Deleted"**

### Description of problem:

Once you select a list that is empty, you cannot show the aliases again - not even when selecting **"All"** again, or selecting the **"Not Deleted"** entry.

If, while you have a selection active that you know to be non-empty, you enter some text in the **"Search aliases"** box (three or more characters), and then remove the text, you will see the aliases again. Or if you close the extension and reopen it you will see the aliases again.

If you have an empty list selected, close the extension and reopen, then select a list that you know to be non-empty, you will **NOT** see those entries. Only doing a search and removing the string, or closing the extension and re-opening will it show the list of aliases again.

Doing a search in a list that is empty does not trigger populating an non-empty list when switching from an empty one to a populated one.

If you exit the extension from an empty list, and re-open the extension, you cannot show any aliases until you do a search on a non-empty list, or close and re-open while a non-empty list is active.

### Steps to replicate this behaviour:

1. Activate extension
2. Aliases are shown (Only if the default of All is already selected)
3. Select a known empty list
4. No aliases are shown
5. Select a known non-empty list
6. No aliases are shown
7. Type a string of three or more characters in to the search box
8. Remove the string from the search box
9. The aliases are shown

**Comment by willbrowningme** [comment]
Thanks for bringing this to my attention, I've just fixed it in v2.2.7 which should be updated on Chrome/Firefox soon.
