### ISSUE TITLE
Thunderbird extension

### ISSUE THREAD

**Issue by fungs** [anonaddy/browser-extension#48]
I know that might be a completely separate project. IMO a thunderbird extension would be most valuable because that's where people work most with email. Right now, I need to open up the standalone web app or browser to create aliases or to send an email using an alias.

Dynamic sender alias selection in thunderbird would be the best!

(Anon)addy is great work!

**Comment by willbrowningme** [comment]
Thanks for the suggestion and feedback! I'm afraid I don't have any plans to create a Thunderbird extension at this time.
