### ISSUE TITLE
[browser extension] Please give me a way to enter a new API key!

### ISSUE THREAD

**Issue by businessBoris** [anonaddy/browser-extension#50]
Hi,

I'm getting regular messages about the API key expiring in x days, but I have no way that I can find in the extension, of invalidating the old/current key and/or entering a new one.

Please can I have such a button/pop-up. I have made a new API key a few days ago but I really really can't find such a button.
Thank you.

There's a pretty pop-up with appropriate options in your lovely app. 
Thank you for everything you've done with this idea.

**Comment by willbrowningme** [comment]
Thanks, that's a good idea.

At the moment you need to click on the "Settings" tab of the browser extension, scroll down to the bottom and then click "Logout". This will allow you to enter your new API key.

**Comment by businessBoris** [comment]
OK problem solved. That's enough for me.

**Comment by willbrowningme** [comment]
I've just added an option to the settings tab to renew your API Key, thanks for the suggestion.

**Comment by businessBoris** [comment]
That's a kind thing to do for dim users like me. Thank-you.

Could you give the app a little love like the Firefox add-on. The add-on has "Tab to show on open" which would be outstanding on the app. I don't care about my stats; I'm on a phone call and the caller/ee is asking for my email address. 

Almost without exception, I want to create an alias when I reach for the app, but there's no easy default. Ok, I understand, it's two buttons to press and you're kept busy ..

I'll get my coat. Taxi for one .. 

Thank-you very much again.  Kind regards.

**Comment by businessBoris** [comment]
I screwed up. Many apologies.
No, not AddyManager, which was on Play. 
I'm writing of addy.io on F-Droid, which, because it wasn't AddyManager and open source, I assumed was yours.
It's not even on Github.
Again, apologies for the confusion; I have no excuse.
