### ISSUE TITLE
permission needed on Firefox but no permission is required

### ISSUE THREAD

**Issue by AnthillSudoku** [anonaddy/browser-extension#51]
just updated Firefox addon to version 2.3.2 and now addy icon shows a point underneath it, hovering the mouse a message appears stating "permission needed".
But if I go to permission tab in addy extensions "This extension doesn’t require any permissions" is shown

**Comment by willbrowningme** [comment]
This is probably because I've updated the manifest version from v2 to v3.

Is everything else working as expected?
