### ISSUE TITLE
Allow custom domain (self-hosted)

### ISSUE THREAD

**Issue by crazy-max** [anonaddy/browser-extension#9]
As AnonAddy could be self-hosted it would be nice to be able to define our own domain.

**Comment by willbrowningme** [comment]
Good idea, I'll try to update the extension with some new features as soon as I can!

**Comment by willbrowningme** [comment]
This has just been added in v1.1.0 of the browser extension, it's already live on FireFox and currently pending for Chrome.

When entering your API token you just need to select "change instance" at the bottom and enter your own AnonAddy location.

You can also now choose an alias format of "custom" and manually enter the local part of the alias.

**Comment by crazy-max** [comment]
@willbrowningme Very nice I will take a shot!
